version: '3.9'
services:
  radicale:
    image: tomsquest/docker-radicale:3.2.3.1
    container_name: radicale
    user: ${UID}:${GID}
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    #   - TZ=${TZ}
    # dns:
    #   - ${DNS_IP}
    volumes:
      - '${APP_DATA_DIR}/data:/data'
      - '${APP_DATA_DIR}/data/config:/config'
      # - '${APP_DATA_DIR}/data/users:/etc/radicale/users'
    ports:
      - ${APP_PORT}:5232
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.radicale-web-redirect.redirectscheme.scheme: https
      traefik.http.services.radicale.loadbalancer.server.port: 5232
      # Web
      traefik.http.routers.radicale-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.radicale-insecure.entrypoints: web
      traefik.http.routers.radicale-insecure.service: radicale
      traefik.http.routers.radicale-insecure.middlewares: radicale-web-redirect
      # Websecure
      traefik.http.routers.radicale.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.radicale.entrypoints: websecure
      traefik.http.routers.radicale.service: radicale
      traefik.http.routers.radicale.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.radicale-local-insecure.rule: Host(`radicale.${LOCAL_DOMAIN}`)
      traefik.http.routers.radicale-local-insecure.entrypoints: web
      traefik.http.routers.radicale-local-insecure.service: radicale
      traefik.http.routers.radicale-local-insecure.middlewares: radicale-web-redirect
      # Local domain secure
      traefik.http.routers.radicale-local.rule: Host(`radicale.${LOCAL_DOMAIN}`)
      traefik.http.routers.radicale-local.entrypoints: websecure
      traefik.http.routers.radicale-local.service: radicale
      traefik.http.routers.radicale-local.tls: true
      runtipi.managed: true
